development:
  cloud_name: "golden-owl-clound"
  api_key: "173569679173764"
  api_secret: "UKYxGJiBJBu0dwoeO5m8aKMRB7M"

production:
  cloud_name: "golden-owl-clound"
  api_key: "173569679173764"
  api_secret: "UKYxGJiBJBu0dwoeO5m8aKMRB7M"
