development:
  cloud_name: "golden-owl-cloud"
  api_key: "822396743473826"
  api_secret: "uV14E1E6WTYUpjNa_GvrBGQS04Y"

production:
  cloud_name: "golden-owl-cloud"
  api_key: "822396743473826"
  api_secret: "uV14E1E6WTYUpjNa_GvrBGQS04Y"
