# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_email: golden.owl.test@gmail.com
  secret_key_base: 264e111f2a10c0faa82f65cc689f5a898ce8099db775c92d5186658d447729108abed8453a3ff8ed456423755858514f60dfdbed779f536ff24276e6df629789
  facebook_app_id: 923584137736369
  facebook_app_secret: 6434ffd21c38f0d21dc99a094ad2fe46
  stripe_publishable_key: pk_test_rdN3QxRwQjZ54cVd1F8Tnu9p
  stripe_secret_key: sk_test_Zb4n6Yzw5fv1yQJ8XB18BGJc

test:
  admin_email: golden.owl.test@gmail.com
  secret_key_base: 170445fa6e0f4f9f0d82daef6affec351cdcefabda88c89748205d5935be9d0906b602ad5bbe16a88d296ce2904598d69a0cd453584742975575731cc31cfbbd
  facebook_app_id: 923584137736369
  facebook_app_secret: 6434ffd21c38f0d21dc99a094ad2fe46


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  stripe_publishable_key: <%= ENV['stripe_publishable_key'] %>
  stripe_secret_key: <%= ENV['stripe_publishable_key'] %>
